### ISSUE TITLE
error

### ISSUE THREAD

**Issue by vestige06** [heyanlong/yii2-redis#5]
PHP Warning 'yii\base\ErrorException' with message 'stream_socket_client(): unable to connect to tcp://172.17.0.1:6379,database=0 (Failed to parse address &quot;172.17.0.1:6379,database=0&quot;)' 

in /qdata/www/vendor/heyanlong/yii2-redis/Connection.php:159

Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleError(2, 'stream_socket_c...', '/qdata/www/vend...', 159, Array)
#1 /qdata/www/vendor/heyanlong/yii2-redis/Connection.php(159): stream_socket_client('tcp://172.17.0....', 0, 'Failed to parse...', -1)
#2 /qdata/www/vendor/heyanlong/yii2-redis/Connection.php(41): heyanlong\redis\Connection->connect('172.17.0.1:6379')
#3 /qdata/www/vendor/heyanlong/yii2-redis/Connection.php(72): heyanlong\redis\Connection->open('172.17.0.1:6379')
#4 /qdata/www/vendor/heyanlong/yii2-redis/Connection.php(63): heyanlong\redis\Connection->executeCommand('set', Array)
#5 /qdata/www/backend/controllers/MemberController.php(26): heyanlong\redis\Connection->__call('set', Array)
#6 [internal function]: backend\controllers\MemberController->actionIndex()
#7 /qdata/www/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array)
#8 /qdata/www/vendor/yiisoft/yii2/base/Controller.php(154): yii\base\InlineAction->runWithParams(Array)
#9 /qdata/www/vendor/yiisoft/yii2/base/Module.php(454): yii\base\Controller->runAction('index', Array)
#10 /qdata/www/vendor/yiisoft/yii2/web/Application.php(87): yii\base\Module->runAction('member/index', Array)
#11 /qdata/www/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(yii\web\Request))
#12 /qdata/www/backend/web/index.php(18): yii\base\Application->run()
#13 {main}

**Comment by heyanlong** [comment]
config file error??
